"""
Market Basket Analysis - Association Rule Mining

Pipeline:
    Basket Matrix
        ↓
    Apriori
        ↓
    Frequent Itemsets
        ↓
    Association Rules
        ↓
    Filter by Confidence and Lift
        ↓
    Sort by Lift
        ↓
    Readable Rules

Required library:
    mlxtend

Install:
    pip install mlxtend pandas
"""

from pathlib import Path
from typing import Optional

import pandas as pd
from mlxtend.frequent_patterns import apriori, association_rules


def load_basket(
    file_path: str | Path = "outputs/basket_matrix.csv"
) -> pd.DataFrame:
    """
    Load the binary basket matrix created by preprocessing.py.

    The first column contains the BillNo transaction ID.
    """

    file_path = Path(file_path)

    if not file_path.exists():
        raise FileNotFoundError(
            f"Basket matrix not found:\n{file_path}\n\n"
            "Run preprocessing.py first."
        )

    print("\n" + "=" * 60)
    print("LOADING BASKET MATRIX")
    print("=" * 60)

    basket = pd.read_csv(
        file_path,
        index_col=0
    )

    # Make sure basket values are binary.
    basket = (
        basket > 0
    ).astype(int)

    print(
        f"Basket shape: {basket.shape}"
    )

    print(
        f"Transactions: {basket.shape[0]:,}"
    )

    print(
        f"Products    : {basket.shape[1]:,}"
    )

    return basket


def find_frequent_itemsets(
    basket: pd.DataFrame,
    min_support: float = 0.02,
    use_colnames: bool = True
) -> pd.DataFrame:
    """
    Find frequent itemsets using the Apriori algorithm.

    Parameters
    ----------
    basket:
        Binary transaction-product matrix.

    min_support:
        Minimum support required for an itemset.

        Example:
            0.05 = itemset must appear in at least 5%
            of all transactions.

    use_colnames:
        Return product names instead of column indexes.
    """

    if basket.empty:
        raise ValueError(
            "Basket matrix is empty."
        )

    if not 0 < min_support <= 1:
        raise ValueError(
            "min_support must be between 0 and 1."
        )

    print("\n" + "=" * 60)
    print("APRIORI FREQUENT ITEMSET MINING")
    print("=" * 60)

    print(
        f"Minimum support: {min_support:.2%}"
    )

    print(
        "\nRunning Apriori..."
    )

    frequent_itemsets = apriori(
        basket,
        min_support=min_support,
        use_colnames=use_colnames
    )

    if frequent_itemsets.empty:
        print(
            "\nNo frequent itemsets found."
        )
        print(
            "Try lowering min_support."
        )

        return frequent_itemsets

    # Number of products in each itemset.
    frequent_itemsets["itemset_size"] = (
        frequent_itemsets["itemsets"]
        .apply(len)
    )

    frequent_itemsets = frequent_itemsets.sort_values(
        by=["support", "itemset_size"],
        ascending=[False, True]
    ).reset_index(drop=True)

    print(
        f"\nFrequent itemsets found: "
        f"{len(frequent_itemsets):,}"
    )

    return frequent_itemsets


def generate_association_rules(
    frequent_itemsets: pd.DataFrame,
    metric: str = "confidence",
    min_threshold: float = 0.3
) -> pd.DataFrame:
    """
    Generate association rules from frequent itemsets.

    The project specification uses:

        metric="confidence"
        min_threshold=0.3
    """

    if frequent_itemsets.empty:
        print(
            "\nNo frequent itemsets available."
        )

        return pd.DataFrame()

    print("\n" + "=" * 60)
    print("GENERATING ASSOCIATION RULES")
    print("=" * 60)

    print(
        f"Metric        : {metric}"
    )

    print(
        f"Minimum value : {min_threshold:.2f}"
    )

    rules = association_rules(
        frequent_itemsets,
        metric=metric,
        min_threshold=min_threshold
    )

    if rules.empty:
        print(
            "\nNo association rules found."
        )

        return rules

    print(
        f"\nRules generated: {len(rules):,}"
    )

    return rules


def filter_rules(
    rules: pd.DataFrame,
    min_confidence: float = 0.5,
    min_lift: float = 1.0
) -> pd.DataFrame:
    """
    Filter association rules.

    Final project specification:

        confidence >= 0.5
        lift > 1

    Parameters
    ----------
    rules:
        Association rules generated by mlxtend.

    min_confidence:
        Minimum confidence threshold.

    min_lift:
        Minimum lift threshold.

    Returns
    -------
    pd.DataFrame
        Filtered and sorted rules.
    """

    if rules.empty:
        print(
            "\nNo rules available for filtering."
        )

        return rules

    print("\n" + "=" * 60)
    print("FILTERING ASSOCIATION RULES")
    print("=" * 60)

    print(
        f"Minimum confidence: {min_confidence:.2f}"
    )

    print(
        f"Minimum lift      : {min_lift:.2f}"
    )

    filtered = rules[
        (rules["confidence"] >= min_confidence)
        & (rules["lift"] > min_lift)
    ].copy()

    # Sort strongest lift first.
    filtered = filtered.sort_values(
        by="lift",
        ascending=False
    ).reset_index(drop=True)

    print(
        f"\nRules before filtering: "
        f"{len(rules):,}"
    )

    print(
        f"Rules after filtering : "
        f"{len(filtered):,}"
    )

    return filtered


def itemsets_to_string(
    itemset
) -> str:
    """
    Convert a frozenset of product names
    into a readable comma-separated string.

    Example:

        frozenset({"BREAD", "MILK"})

    becomes:

        BREAD, MILK
    """

    if not itemset:
        return ""

    return ", ".join(
        sorted(
            str(item)
            for item in itemset
        )
    )


def make_rules_readable(
    rules: pd.DataFrame
) -> pd.DataFrame:
    """
    Convert frozenset antecedents/consequents
    into readable product strings.

    Also keeps the main rule metrics.
    """

    if rules.empty:
        return rules.copy()

    readable = rules.copy()

    readable["antecedents"] = (
        readable["antecedents"]
        .apply(itemsets_to_string)
    )

    readable["consequents"] = (
        readable["consequents"]
        .apply(itemsets_to_string)
    )

    # Select useful columns when available.
    preferred_columns = [
        "antecedents",
        "consequents",
        "antecedent support",
        "consequent support",
        "support",
        "confidence",
        "lift",
    ]

    columns = [
        column
        for column in preferred_columns
        if column in readable.columns
    ]

    readable = readable[
        columns
    ]

    return readable


def format_rules(
    rules: pd.DataFrame
) -> pd.DataFrame:
    """
    Add a human-readable rule column.

    Example:

        BREAD -> MILK
    """

    if rules.empty:
        return rules.copy()

    formatted = rules.copy()

    if {
        "antecedents",
        "consequents"
    }.issubset(formatted.columns):

        formatted["rule"] = (
            formatted["antecedents"]
            + " -> "
            + formatted["consequents"]
        )

        columns = [
            "rule",
            "support",
            "confidence",
            "lift",
        ]

        columns = [
            column
            for column in columns
            if column in formatted.columns
        ]

        formatted = formatted[
            columns
        ]

    return formatted


def mine_rules(
    basket: pd.DataFrame,
    min_support: float = 0.02,
    min_confidence: float = 0.5,
    min_lift: float = 1.0
) -> tuple[pd.DataFrame, pd.DataFrame]:
    """
    Complete market basket mining pipeline.

    Steps:
        1. Apriori frequent itemsets
        2. Association rule generation
        3. Confidence filtering
        4. Lift filtering
        5. Readable rule formatting

    Returns
    -------
    frequent_itemsets, final_rules
    """

    frequent_itemsets = find_frequent_itemsets(
        basket,
        min_support=min_support
    )

    if frequent_itemsets.empty:
        return (
            frequent_itemsets,
            pd.DataFrame()
        )

    rules = generate_association_rules(
        frequent_itemsets,
        metric="confidence",
        min_threshold=0.3
    )

    if rules.empty:
        return (
            frequent_itemsets,
            rules
        )

    filtered_rules = filter_rules(
        rules,
        min_confidence=min_confidence,
        min_lift=min_lift
    )

    readable_rules = make_rules_readable(
        filtered_rules
    )

    final_rules = format_rules(
        readable_rules
    )

    return (
        frequent_itemsets,
        final_rules
    )


def display_top_rules(
    rules: pd.DataFrame,
    top_n: int = 20
) -> None:
    """
    Display the strongest association rules.
    """

    print("\n" + "=" * 60)
    print("TOP ASSOCIATION RULES")
    print("=" * 60)

    if rules.empty:
        print(
            "No rules satisfy the selected thresholds."
        )
        return

    display_columns = [
        column
        for column in [
            "rule",
            "support",
            "confidence",
            "lift"
        ]
        if column in rules.columns
    ]

    top_rules = rules[
        display_columns
    ].head(top_n).copy()

    # Make metrics easier to read.
    for column in [
        "support",
        "confidence"
    ]:
        if column in top_rules.columns:
            top_rules[column] = (
                top_rules[column]
                .map(lambda value: f"{value:.2%}")
            )

    if "lift" in top_rules.columns:
        top_rules["lift"] = (
            top_rules["lift"]
            .map(lambda value: f"{value:.2f}")
        )

    print(
        top_rules.to_string(
            index=False
        )
    )


def save_results(
    frequent_itemsets: pd.DataFrame,
    rules: pd.DataFrame,
    output_dir: str | Path = "outputs"
) -> None:
    """
    Save frequent itemsets and final association rules.
    """

    output_dir = Path(
        output_dir
    )

    output_dir.mkdir(
        parents=True,
        exist_ok=True
    )

    itemsets_path = (
        output_dir /
        "frequent_itemsets.csv"
    )

    rules_path = (
        output_dir /
        "association_rules.csv"
    )

    # Convert itemsets to strings before saving.
    itemsets_to_save = frequent_itemsets.copy()

    if not itemsets_to_save.empty:
        itemsets_to_save["itemsets"] = (
            itemsets_to_save["itemsets"]
            .apply(itemsets_to_string)
        )

    itemsets_to_save.to_csv(
        itemsets_path,
        index=False
    )

    rules.to_csv(
        rules_path,
        index=False
    )

    print("\n" + "=" * 60)
    print("MINING RESULTS SAVED")
    print("=" * 60)

    print(
        f"Frequent itemsets : {itemsets_path}"
    )

    print(
        f"Association rules : {rules_path}"
    )


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(
        description=(
            "Run Apriori and association "
            "rule mining."
        )
    )

    parser.add_argument(
        "--input",
        default="outputs/basket_matrix.csv",
        help=(
            "Path to the basket matrix "
            "created by preprocessing.py."
        )
    )

    parser.add_argument(
        "--output",
        default="outputs",
        help=(
            "Directory for mining results."
        )
    )

    parser.add_argument(
        "--min-support",
        type=float,
        default=0.02,
        help=(
            "Minimum support for Apriori. "
            "Default: 0.02"
        )
    )

    parser.add_argument(
        "--min-confidence",
        type=float,
        default=0.5,
        help=(
            "Minimum confidence for final rules. "
            "Default: 0.5"
        )
    )

    parser.add_argument(
        "--min-lift",
        type=float,
        default=1.0,
        help=(
            "Minimum lift for final rules. "
            "Default: 1.0"
        )
    )

    parser.add_argument(
        "--top",
        type=int,
        default=20,
        help=(
            "Number of top rules to display. "
            "Default: 20"
        )
    )

    args = parser.parse_args()

    basket = load_basket(
        args.input
    )

    frequent_itemsets, final_rules = mine_rules(
        basket=basket,
        min_support=args.min_support,
        min_confidence=args.min_confidence,
        min_lift=args.min_lift
    )

    display_top_rules(
        final_rules,
        top_n=args.top
    )

    save_results(
        frequent_itemsets,
        final_rules,
        args.output
    )

    print("\n" + "=" * 60)
    print("MARKET BASKET MINING COMPLETE")
    print("=" * 60)