"""
Market Basket Analysis - Visualization

Visualizations:
    1. Support vs Confidence scatter plot
    2. Bubble size represents Lift

Input:
    outputs/association_rules.csv

Output:
    outputs/association_rules_plot.png
"""

from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd


def load_rules(
    file_path: str | Path = "outputs/association_rules.csv"
) -> pd.DataFrame:
    """
    Load association rules generated by market_basket.py.
    """

    file_path = Path(file_path)

    if not file_path.exists():
        raise FileNotFoundError(
            f"Association rules file not found:\n{file_path}\n\n"
            "Run market_basket.py first."
        )

    print("\n" + "=" * 60)
    print("LOADING ASSOCIATION RULES")
    print("=" * 60)

    rules = pd.read_csv(file_path)

    if rules.empty:
        raise ValueError(
            "Association rules file is empty."
        )

    required_columns = [
        "support",
        "confidence",
        "lift",
    ]

    missing_columns = [
        column
        for column in required_columns
        if column not in rules.columns
    ]

    if missing_columns:
        raise ValueError(
            "Missing required columns: "
            + ", ".join(missing_columns)
        )

    print(
        f"Rules loaded: {len(rules):,}"
    )

    return rules


def prepare_rules(
    rules: pd.DataFrame
) -> pd.DataFrame:
    """
    Prepare rule metrics for plotting.
    """

    data = rules.copy()

    for column in [
        "support",
        "confidence",
        "lift",
    ]:
        data[column] = pd.to_numeric(
            data[column],
            errors="coerce"
        )

    data = data.dropna(
        subset=[
            "support",
            "confidence",
            "lift",
        ]
    )

    # Lift must be positive for sensible bubble sizing.
    data = data[
        data["lift"] > 0
    ]

    if data.empty:
        raise ValueError(
            "No valid rules available for visualization."
        )

    return data


def plot_support_confidence(
    rules: pd.DataFrame,
    output_path: str | Path = (
        "outputs/association_rules_plot.png"
    ),
    show_plot: bool = True,
) -> None:
    """
    Create a Support vs Confidence scatter plot.

    X-axis:
        Support

    Y-axis:
        Confidence

    Bubble size:
        Lift
    """

    data = prepare_rules(rules)

    output_path = Path(output_path)

    output_path.parent.mkdir(
        parents=True,
        exist_ok=True
    )

    print("\n" + "=" * 60)
    print("CREATING ASSOCIATION RULE VISUALIZATION")
    print("=" * 60)

    # Scale lift so bubbles are visible without
    # making extremely high-lift rules dominate.
    bubble_sizes = (
        data["lift"] * 80
    ).clip(
        lower=40,
        upper=1500
    )

    plt.figure(
        figsize=(10, 7)
    )

    plt.scatter(
        data["support"],
        data["confidence"],
        s=bubble_sizes,
        alpha=0.6,
        edgecolors="black",
        linewidths=0.5,
    )

    plt.xlabel(
        "Support"
    )

    plt.ylabel(
        "Confidence"
    )

    plt.title(
        "Association Rules: Support vs Confidence"
    )

    plt.grid(
        True,
        alpha=0.25
    )

    # Display percentages on both axes.
    plt.gca().xaxis.set_major_formatter(
        plt.FuncFormatter(
            lambda value, _: f"{value:.0%}"
        )
    )

    plt.gca().yaxis.set_major_formatter(
        plt.FuncFormatter(
            lambda value, _: f"{value:.0%}"
        )
    )

    plt.tight_layout()

    plt.savefig(
        output_path,
        dpi=300,
        bbox_inches="tight"
    )

    print(
        f"\nPlot saved to:\n{output_path}"
    )

    if show_plot:
        plt.show()

    plt.close()


def plot_top_rules(
    rules: pd.DataFrame,
    top_n: int = 10,
    output_path: str | Path = (
        "outputs/top_association_rules.png"
    ),
    show_plot: bool = True,
) -> None:
    """
    Create a horizontal bar chart showing the
    lift values of the strongest rules.

    This is an additional visualization that can
    help interpret the mined rules.
    """

    data = prepare_rules(rules)

    if "rule" not in data.columns:
        data["rule"] = (
            data["antecedents"].astype(str)
            + " -> "
            + data["consequents"].astype(str)
        )

    data = (
        data.sort_values(
            "lift",
            ascending=False
        )
        .head(top_n)
        .sort_values(
            "lift",
            ascending=True
        )
    )

    if data.empty:
        return

    output_path = Path(output_path)

    output_path.parent.mkdir(
        parents=True,
        exist_ok=True
    )

    print("\n" + "=" * 60)
    print("CREATING TOP RULES VISUALIZATION")
    print("=" * 60)

    plt.figure(
        figsize=(11, 7)
    )

    plt.barh(
        data["rule"],
        data["lift"],
        alpha=0.8
    )

    plt.xlabel(
        "Lift"
    )

    plt.ylabel(
        "Association Rule"
    )

    plt.title(
        f"Top {min(top_n, len(data))} Association Rules by Lift"
    )

    plt.grid(
        axis="x",
        alpha=0.25
    )

    plt.tight_layout()

    plt.savefig(
        output_path,
        dpi=300,
        bbox_inches="tight"
    )

    print(
        f"\nPlot saved to:\n{output_path}"
    )

    if show_plot:
        plt.show()

    plt.close()


def visualize(
    rules_file: str | Path = (
        "outputs/association_rules.csv"
    ),
    output_dir: str | Path = "outputs",
    top_n: int = 10,
    show_plot: bool = True,
) -> None:
    """
    Run the complete visualization pipeline.
    """

    output_dir = Path(output_dir)

    rules = load_rules(
        rules_file
    )

    plot_support_confidence(
        rules=rules,
        output_path=(
            output_dir /
            "association_rules_plot.png"
        ),
        show_plot=show_plot,
    )

    # Additional interpretation plot.
    plot_top_rules(
        rules=rules,
        top_n=top_n,
        output_path=(
            output_dir /
            "top_association_rules.png"
        ),
        show_plot=show_plot,
    )

    print("\n" + "=" * 60)
    print("VISUALIZATION COMPLETE")
    print("=" * 60)


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(
        description=(
            "Visualize Market Basket "
            "Association Rules."
        )
    )

    parser.add_argument(
        "--input",
        default="outputs/association_rules.csv",
        help=(
            "Path to association_rules.csv."
        )
    )

    parser.add_argument(
        "--output",
        default="outputs",
        help=(
            "Directory for visualization outputs."
        )
    )

    parser.add_argument(
        "--top",
        type=int,
        default=10,
        help=(
            "Number of top rules for the "
            "additional lift chart."
        )
    )

    parser.add_argument(
        "--no-show",
        action="store_true",
        help=(
            "Save plots without displaying them."
        )
    )

    args = parser.parse_args()

    visualize(
        rules_file=args.input,
        output_dir=args.output,
        top_n=args.top,
        show_plot=not args.no_show,
    )